project/account/urls.py
from django.urls import path
from account import views
from account.api import views as apiViews

app_name = 'account'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.signout, name='signout'),
    path('reAuthenticate/', views.re_authenticate, name='reAuthenticate'),
    path('editProfile/', views.editProfile, name='editProfile'),
    path('imageUpload/', views.imageUpload, name='imageUpload'),
    path('deleteImage/', views.deleteImage, name='deleteImage'),
    path('', views.profile, name='profile'),
    path('api/hw', apiViews.hello_world, name='hello_world'),
    path('api/signup/', apiViews.createUserView, name='signupAPI'),
    path('api/signin/', apiViews.loginUserView, name='signinAPI'),
    path('api/editProfile/', apiViews.editUserProfileView, name='editProfileAPI'),
    path('api/delete/', apiViews.deleteUserView, name='deleteAPI'),
    path('api/photo/', apiViews.photoView.as_view(), name='photoUpload'),
]

project/newsBlog/urls.py
from django.urls import path
from .views import list,detail,comment,deletePost
from newsBlog.api.views import getPostView,editPostView,getComment,editComment

app_name = 'newsBlog'

urlpatterns = [
	path('' ,list ,name = 'list'),
	path('<int:year>/<int:month>/<int:day>/<slug:post>/', detail, name = 'detail'),
	path('getComment/' ,getComment ,name = 'getComment'),
	path('editComment/' ,editComment ,name = 'editComment'),
	path('comment/' ,comment ,name = 'comment'),
	path('deletePost/' ,deletePost ,name = 'deletePost'),
	path('api/getPost/' ,getPostView ,name = 'getPost'),
	path('api/editPost/' ,editPostView ,name = 'editPost'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.homeView),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls','account')),
    path('news/',include('newsBlog.urls','news')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/newsBlog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from django.utils.translation import ugettext_lazy as _
from taggit.models import GenericUUIDTaggedItemBase, TaggedItemBase
import uuid


#Custom model manager to filter posts according to published status
class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager,self).get_queryset()\
										   .filter(status='published')

class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):
    # If you only inherit GenericUUIDTaggedItemBase, you need to define
    # a tag field. e.g.
    # tag = models.ForeignKey(Tag, related_name="uuid_tagged_items", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")


# Create your models here.
class Post(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	STATUS_CHOICES = (
		('draft', 'Draft'),
		('published', 'Published'),
	)
	title = models.CharField(max_length=250,blank=False)
	slug = models.SlugField(max_length=250,unique_for_date='publish',blank=False)
	body = models.TextField(blank=False)
	thumbnail = models.CharField(max_length=50,blank=True,default='WLUHO9A_xik',help_text='ONLY PHOTOS UPLOADED TO SERVER!!')
	author = models.ForeignKey(User, on_delete=models.CASCADE,related_name='newsBlog_post')
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
	objects = models.Manager() #Django's default model manager/filterer
	published = PublishedManager() #Our custom model manager/filterer
	tags = TaggableManager(through=UUIDTaggedItem)
	class Meta:
		ordering = ('-publish',)
	def __str__(self):
		 return self.title
	def get_absolute_url(self):
		 return reverse('newsBlog:detail',args=[self.publish.year,
		 										self.publish.month,
												self.publish.day, self.slug])

	def get_admin_url(self):
		return '/admin/newsBlog/post/'+self.pk+'/change/'


class Comment(models.Model):
	post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
	name = models.CharField(max_length=50)
	username = models.CharField(max_length=150)
	body = models.TextField(blank=False)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)
	class Meta:
		ordering = ('-created',)
	def __str__(self):
		return f'Comment by {self.name} on {self.post}'
   

project/newsBlog/api/views.py
from rest_framework.decorators import api_view
from rest_framework.parsers import JSONParser
from django.http import JsonResponse
from newsBlog.api.serializers import GetPostSerializer, CreatePostSerializer, EditPostSerializer, DeletePostSerializer,GetCommentSerializer,CreateCommentSerializer,EditCommentSerializer,DeleteCommentSerializer
from rest_framework.decorators import authentication_classes, permission_classes
from rest_framework.authtoken.models import Token



@api_view(['GET'])
@authentication_classes([])
@permission_classes([])
def getPostView(request):
    if request.method == 'GET':
        data = JSONParser().parse(request)
        serializer = GetPostSerializer(data=data)
        if serializer.is_valid():
            data = serializer.create(data)
            return JsonResponse({"data":list(data)})
        return JsonResponse(serializer.errors, status=400)



@api_view(['POST','PUT','DELETE'])
def editPostView(request):
    if request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = CreatePostSerializer(data=data)
        if serializer.is_valid():
            data = serializer.create(data)
            return JsonResponse(data)
        return JsonResponse(serializer.errors, status=400)

    if request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = EditPostSerializer(data=data)
        if serializer.is_valid():
            data = serializer.create(data)
            return JsonResponse(data)
        return JsonResponse(serializer.errors, status=400)
    
    if request.method == 'DELETE':
        data = JSONParser().parse(request)
        serializer = DeletePostSerializer(data=data)
        if serializer.is_valid():
            data = serializer.create(data)
            return JsonResponse(data)
        return JsonResponse(serializer.errors, status=400)



@api_view(['GET'])
@authentication_classes([])
@permission_classes([])
def getComment(request):
    if request.method == 'GET':
        data = JSONParser().parse(request)
        serializer = GetCommentSerializer(data=data)
        if serializer.is_valid():
            data = serializer.create(data)
            return JsonResponse({"data":list(data)})
        return JsonResponse(serializer.errors, status=400)


@api_view(['POST','PUT','DELETE'])
def editComment(request):
    if request.method == 'POST':
        data = JSONParser().parse(request)
        token = request.headers['Authorization']+""
        token = token.replace("Token ", "")
        user = Token.objects.get(key=token).user
        serializer = CreateCommentSerializer(data=data)
        if serializer.is_valid():
            data = serializer.create(data,user)
            return JsonResponse(data)
        return JsonResponse(serializer.errors, status=400)

    if request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = EditCommentSerializer(data=data)
        if serializer.is_valid():
            data = serializer.create(data)
            return JsonResponse(data)
        return JsonResponse(serializer.errors, status=400)
    
    if request.method == 'DELETE':
        data = JSONParser().parse(request)
        serializer = DeleteCommentSerializer(data=data)
        if serializer.is_valid():
            data = serializer.create(data)
            return JsonResponse(data)
        return JsonResponse(serializer.errors, status=400)

project/newsBlog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.paginator import Paginator

#======================LIST VIEW========================
def list(request):
    searchorfiltered = False
    filters = request.GET.get("filters")
    if filters is not None:
        allPosts = Post.published.filter(tags__name__in=[filters])
        searchorfiltered = True
    else:
        allPosts = Post.published.all()

    search = request.GET.get("search")
    if search is not None:
        search = search.replace("+"," ")
        allPosts = allPosts.filter(title__icontains=""+search)
        searchorfiltered = True

    paginator = Paginator(allPosts, 5)
    page_number = request.GET.get("page")
    posts = paginator.get_page(page_number)

    return render(request,'newsBlog/files/listBlog.html',{'nav':'common/nav.html','posts':posts,'css':'newsBlog/files/listBlogCss.html','js':'newsBlog/files/listBlogJs.html','searchorfiltered':searchorfiltered})
#====================END LIST VIEW=======================




#======================DETAIL VIEW========================
def detail(request,year,month,day,post):
	post = get_object_or_404(Post, slug=post, status='published', publish__year=year,publish__month=month, publish__day=day,)

	comments = post.comments.filter(active=True)
	

	return render(request,'newsBlog/files/detailBlog.html',{'nav':'common/nav.html','css':'newsBlog/files/detailBlogCss.html','post':post,'comments':comments,'js':'newsBlog/files/detailBlogJs.html',})
#====================END DETAIL VIEW=======================




@login_required
@require_POST
def comment(request):
	post = get_object_or_404(Post, slug=request.POST.get('slug'), status='published', publish__year=request.POST.get('year'),publish__month=request.POST.get('month'), publish__day=request.POST.get('day'))
	newComment = request.POST.get('newComment')
	newCommentModel = Comment()
	newCommentModel.post = post
	newCommentModel.name = request.user.first_name
	newCommentModel.username = request.user.username
	newCommentModel.body = newComment
	newCommentModel.save()
	return JsonResponse({'status':'ok'})


@login_required
@require_POST
def deletePost(request):
    post = Post.objects.filter(author=request.user,id=request.POST.get("id"))
    post.delete()
    return JsonResponse({'status':'ok'})

project/templates/newsBlog/files/detailBlog.html
{% extends "newsBlog/base.html" %}
{% load model_extras %}
<!--=====================TITLE==================-->
{% block title %}
{{ post.title }}
{% endblock title %}
<!--===================END TITLE=================-->
<!--======================CSS====================-->
{% block css %}
{% include css %}
{% endblock css %}
<!--====================END CSS===================-->
<!--======================JS====================-->
{% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js"></script>
{% include js %}
{% endblock js %}
<!--====================END JS===================-->
<!--======================CONTENT====================-->

{% block content %}
<div id="container">
    <div id="postThumbnail">
        <img src="/media/{{post.thumbnail}}" alt="">
        <div id="after"></div>
    </div>
    <div id="innerContainer">
        <div id="postTitle">{{post.title}}</div>
        <div id="postAuthor">~by <span style="text-transform: capitalize;">{{ post.author }}</span>&nbsp;&middot;&nbsp;{{ post|time_difference }}</div>
        <div id="postBody">{{post.body}}</div>
    </div>
    <div id="comments">
        <div id="head">
            Comments
        </div>
        <div id="postComment">
            {% if request.user.is_authenticated %}
            <div>
                <div id="commentContainer">
                    <textarea onfocus="" id="newCommentInput" placeholder="Enter your comment"></textarea>
                    <div onclick="newCommentSend()" style="background-image: url(/media/assets/send.svg);background-size: 100%;background-repeat: no-repeat;"></div>
                </div>
            </div>
            {% else %}
            <div id="signinPrompt">
                Please &nbsp; <a href="/account/signin/" style="font-weight: bold;font-variant: small-caps;" target="_blank">sign in</a> &nbsp;to post comments!
            </div>
            {% endif %}
        </div>
        <hr style="height:1px;border-width:0;color:lightgray;background-color:lightgray">
        <div id="allComments">
            {% for comment in comments %}
            <div style="display:inline-block;margin-bottom: 5px;">{{ comment.name }}</div>
            <br><span style="color: lightgrey;">&emsp;&emsp;{{ comment.body }}</span><br>
            <hr style="height:1px;border-width:0;color:rgb(114, 114, 114);background-color:rgb(114, 114, 114)">
            {% empty %}
            No Comments
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}
<!--====================END CONTENT===================-->

project/templates/newsBlog/files/detailBlogCss.html
<style>
    #content {
        margin: 0;
    }

    #homeL {
        display: none;
    }

    #container {
        position: relative;
        width: 100%;
        height: auto;
        overflow: hidden;
        margin-bottom: 10vh;
    }



    /*=======================THUMBNAIL======================*/
    #postThumbnail {
        position: relative;
        width: 120%;
        overflow: hidden;
        margin: -10px auto 0 -20px;
        z-index: -10;
    }

    #postThumbnail #after {
        background: linear-gradient(0deg, rgba(51, 57, 69, 1) 0%, rgba(255, 255, 255, 0) 100%);
        width: 100%;
        height: 70%;
        position: absolute;
        bottom: 0;
        left: 0;
    }

    #postThumbnail img {
        width: inherit;
        height: inherit;
        object-fit: cover;
        object-position: center;
        filter: brightness(0.5);
    }

    /*=====================END THUMBNAIL=====================*/




    /*=======================POST CONTENT======================*/
    #innerContainer {
        width: 75%;
        height: auto;
        color: white;
        margin: -150px 0 20px 0;
        border-radius: 10px;
        padding: 15px;
        box-shadow: 1px 1px 6px 0px black;
        background-color: #2C3335;
    }

    #postTitle,
    #comments #head {
        font-family: 'Spartan', sans-serif;
        font-weight: bold;
        font-variant: small-caps;
        text-transform: capitalize;
        margin-top: 10px;
        color: white;
    }

    #postBody {
        font-size: 17px;
        text-align: justify;
        padding: 5px;
        font-family: 'Spartan', sans-serif;
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        overflow: hidden;
    }

    #postBody h1,
    #postBody h2,
    #postBody h3,
    #postBody h4,
    #postBody h5,
    #postBody h6 {
        text-align: left;
        width: 100%;
    }

    #postBody pre,
    #postBody pre code {
        width: 90%;
        white-space: pre-wrap;
        white-space: -moz-pre-wrap;
        white-space: -pre-wrap;
        white-space: -o-pre-wrap;
        word-wrap: break-word;
    }

    #postBody pre{
        border:1px solid #454c4e;
        background-color: #454c4e;
        padding: 3px 5px;
        border-radius: 3px;
    }

    #postBody hr {
        width: 100%;
    }

    #postBody > ul,#postBody > ol {
        width: 100%;
    }

    #postBody table{
        border-collapse: collapse !important;
    }

    #postBody table  * {
        border: 2px solid gray !important;
        padding: 5px;
    }

    #postBody a{
        color: white;
        font-weight: bold;
    }

    #postBody img {
        max-width: 75%;
    }

    #postBody img:parent{
        text-align: center;
    }

    #postBody p {
        width: 100%;
    }

    #postAuthor {
        width: 100%;
        text-align: left;
        color: rgb(161, 161, 161);
        padding-left: 15px;
    }

    /*=====================END POST CONTENT====================*/




    /*=======================COMMENT======================*/
    #comments {
        width: 75%;
        height: auto;
        min-height: 10vh;
        box-shadow: 1px 1px 6px 0px black;
        background-color: #2C3335;
        color: white;
        padding: 15px;
        border-radius: 10px;
        text-align: left;
        color: white;
        cursor: default;
        font-family: 'Spartan', sans-serif;
		margin-bottom: 10px;
    }

    #comments #postComment {
        padding: 10px 0;
    }

    #comments #postComment #signinPrompt,
    #comments #postComment #signinPrompt a {
        text-transform: capitalize;
        color: white;
    }

    #comments #head {
        width: 100%;
        text-align: center;
        margin-bottom: 10px;
    }

    #postComment>div {
        width: 90%;
        display: flex;
        justify-content: center;
    }

    #newCommentSubmit {
        width: 0;
        height: 0;
        pointer-events: none;
        background-color: #ff000f;
        color: transparent;
        font-size: 0px;
    }

    #newCommentInput {
        background-color: transparent;
        border: 1px solid #E71C23;
        border-radius: 5px;
        width: 100%;
        color: white;
        outline: none;
        padding: 5px 40px 5px 10px;
        line-break: auto;
        resize: none;
        transition: 0.2s;
    }

    .newCommentInputFocus {
        height: 100px !important;
    }

    #postComment div div {
        position: relative;
    }

    #postComment div div div {
        position: absolute;
        right: -40px;
        bottom: 10px;
        cursor: pointer;
    }

    #newCommentInput::-webkit-scrollbar {
        display: none;
    }

    /*=====================END COMMENT====================*/


    @media (max-width: 319px) {

        /*Very small devices ,*/
        #postThumbnail {
            height: 55vh;
        }

        #postTitle,
        #comments #head {
            font-size: 15px;
        }

        #postBody,
        #postComment,
        #allComments,
        #newCommentInput,
        #postAuthor {
            font-size: 13px;
        }

        #commentContainer {
            width: 75%;
        }

        #postComment div div div {
            width: 15px;
            height: 15px;
        }

        #newCommentInput {
            height: 15px;
        }

		#innerContainer {
			margin: -200px 0 20px 0;
		}

		#innerContainer,#comments{
			width: 85%;
		}
    }

    @media (min-width:320px) {

        /* smartphones, iPhone, portrait 480x320 phones */
        #postThumbnail {
            height: 55vh;
        }

        #postTitle,
        #comments #head {
            font-size: 20px;
        }

        #postBody,
        #postComment,
        #allComments,
        #newCommentInput,
        #postAuthor {
            font-size: 13px;
        }

        #commentContainer {
            width: 75%;
        }

        #postComment div div div {
            width: 15px;
            height: 15px;
        }

        #newCommentInput {
            height: 15px;
        }

		#innerContainer {
			margin: -200px 0 20px 0;
		}

		#innerContainer,#comments{
			width: 85%;
		}
    }

    @media (min-width:481px) {

        /* portrait e-readers (Nook/Kindle), smaller tablets @ 600 or @ 640 wide. */
        #postThumbnail {
            height: 55vh;
        }

        #postTitle,
        #comments #head {
            font-size: 25px;
        }

        #postBody,
        #postComment,
        #allComments,
        #newCommentInput,
        #postAuthor {
            font-size: 15px;
        }

        #commentContainer {
            width: 75%;
        }

        #postComment div div div {
            width: 20px;
            height: 20px;
        }

        #newCommentInput {
            height: 20px;
        }

		#innerContainer {
			margin: -200px 0 20px 0;
		}

		#innerContainer,#comments{
			width: 85%;
		}
    }

    @media (min-width:641px) {

        /* portrait tablets, portrait iPad, landscape e-readers, landscape 800x480 or 854x480 phones */
        #postThumbnail {
            height: 55vh;
        }

        #postTitle,
        #comments #head {
            font-size: 30px;
        }

        #postBody,
        #postComment,
        #allComments,
        #newCommentInput,
        #postAuthor {
            font-size: 15px;
        }

        #commentContainer {
            width: 75%;
        }

        #postComment div div div {
            width: 20px;
            height: 20px;
        }

        #newCommentInput {
            height: 20px;
        }

		#innerContainer {
			margin: -80px 0 20px 0;
		}

		#innerContainer,#comments{
			width: 90%;
		}
    }

    @media (min-width:961px) {

        /* tablet, landscape iPad, lo-res laptops ands desktops */
        #postThumbnail {
            height: 65vh;
        }

        #postTitle,
        #comments #head {
            font-size: 35px;
        }

        #postBody,
        #postComment,
        #allComments,
        #newCommentInput,
        #postAuthor {
            font-size: 17px;
        }

        #commentContainer {
            width: 65%;
        }

        #postComment div div div {
            width: 30px;
            height: 30px;
        }

        #newCommentInput {
            height: 25px;
        }
    }

    @media (min-width:1025px) {

        /* big landscape tablets, laptops, and desktops */
        #postThumbnail {
            height: 65vh;
        }

        #postTitle,
        #comments #head {
            font-size: 35px;
        }

        #postBody,
        #postComment,
        #allComments,
        #newCommentInput,
        #postAuthor {
            font-size: 17px;
        }

        #commentContainer {
            width: 65%;
        }

        #postComment div div div {
            width: 30px;
            height: 30px;
        }

        #newCommentInput {
            height: 25px;
        }
    }

    @media (min-width:1281px) {

        /* hi-res laptops and desktops */
        #postThumbnail {
            height: 65vh;
        }

        #postTitle,
        #comments #head {
            font-size: 35px;
        }

        #postBody,
        #postComment,
        #allComments,
        #newCommentInput,
        #postAuthor {
            font-size: 17px;
        }

        #commentContainer {
            width: 65%;
        }

        #postComment div div div {
            width: 30px;
            height: 30px;
        }

        #newCommentInput {
            height: 25px;
        }
    }
</style>

project/templates/newsBlog/files/detailBlogJs.html
<script>
    var csrftoken = Cookies.get('csrftoken');

    $(document).ready(function () {
        text = $("#postBody").html()
        // $("#postBody").html((new showdown.Converter()).makeHtml(text))
        var md = window.markdownit({
            html: true,
            linkify: true,
            typographer: true
        });
        md.use(window.markdownitEmoji);
        // md.use(window.markdownitSub);
        var result = md.render('' + text);
        $("#postBody").html(result)
    });

    $("#newCommentInput").focusin(function () {
        $(this).addClass("newCommentInputFocus");
    });

    $("#newCommentInput").focusout(function () {
        if ($(this).val().trim() == "") {
            $(this).removeClass("newCommentInputFocus");
        }
    });

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protectio
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    function newCommentSend() {
        var newComment = $("#newCommentInput").val().trim();
        if (newComment != "") {
            var year = '{{post.publish.year}}'
            var month = '{{post.publish.month}}'
            var day = '{{post.publish.day}}'
            var slug = '{{post.slug}}'
            $.post('{% url "newsBlog:comment" %}', {
                    newComment: newComment,
                    year: year,
                    month: month,
                    day: day,
                    slug: slug,
                },
                function (recievedData) {
                    if (recievedData['status'] == 'ok') {
                        $("#allComments").load(window.location.href + " #allComments");
                        var newComment = $("#newCommentInput").val("");
                    }
                });
        }
    }
</script>

project/templates/newsBlog/files/listBlog.html
{% extends "newsBlog/base.html" %}
{% block css %}
{% include css %}
{% endblock css %}
{% block title %}News{% endblock title %}
{% block content %}
<div id="container">
    <!--===============POST LIST==============-->
    <div id="postList">
		<span class="heading">{% if searchorfiltered %}Search Results{% else %}All Posts{% endif %}</span>
        <div id="postContainer">
            {% for post in posts %}
            <div class="post" onclick="document.location.href = '{{ post.get_absolute_url }}'">
                <div class="postTitle">{{ post.title|truncatewords:15 }}</div>
                <img class="postThumbnail" src="/media/{{ post.thumbnail }}">
            </div>
            {% endfor %}
        </div>
<div class="pagination">
    <div class="step-links">
       {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}"><button class="buttonStyle1">Previous</button></a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}"><button class="buttonStyle1">Next</button></a>
        {% endif %}
    </div>
</div>

    </div>
    <!--=============END POST LIST==============-->
</div>
{% endblock %}
{% block extras %}
<!--=============FILTER COLUMN==============-->
<div id="postFilter">
    <div id="innerContainer">
        <div id="navHeading">
            <span id="first">Blind</span><span id="second">craft</span>
        </div>
    </div>
</div>
<!--===========END FILTER COLUMN==============-->
<!--=============FILTER BUTTON==============-->
<div id="filterTrigger">
    <div id="filterTriggerButton" onclick="filterTrigger('open')">
        <span>F</span><br>
        <span>I</span><br>
        <span>L</span><br>
        <span>T</span><br>
        <span>E</span><br>
        <span>R</span><br>
    </div>
</div>
<!--===========END FILTER BUTTON==============-->
{% endblock extras %}
{% block js %}
{% include js %}
{% endblock js %}

project/templates/newsBlog/files/listBlogJs.html
<script>
var filterIsOpened = false;

function filterTrigger(command) {
    if (command == 'open') {
        $('div#postFilter').css('width', '200px');
        $('div#innerContainer').css('transform', 'rotateY(0deg)');
        $('div#filterTrigger').css('display', 'none');
        filterIsOpened = true;
    } else if (command == 'close') {
        $('div#postFilter').css('width', '0px');
        $('div#innerContainer').css('transform', 'rotateY(-90deg)');
        $('div#filterTrigger').css('display', 'flex');
        filterIsOpened = false;
    }

}
$('div#content').click(function() {
    if (filterIsOpened) {
        filterTrigger('close')
    }
});
// $('div#postList').mousemove(function(e) {
//     let xAxis = (window.innerWidth / 2 - e.pageX) / 65;
//     let yAxis = (window.innerWidth / 2 - e.pageY) / 65;

//     $(this).css('transform', 'rotateY(' + xAxis + 'deg) rotateX(' + yAxis + 'deg)');
// });

// $('div#postList').mouseenter(function() {
//     $(this).css('transition', 'none')
// })

// $('div#postList').mouseleave(function() {
//     $(this).css('transition', 'all 0.5s ease')
//     $(this).css('transform', 'rotateY(0deg) rotateX(0deg)');
// });
</script>